<?php

function secsyn_node_menu() {
  return array(
    'node/%node/syndicate' => array(
      'title' => 'Syndicate',
      'description' => 'Syndicate an object to a remote server',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('secsyn_node_syndicate_form', 1),
      'access arguments' => array('syndicate object'),
      'file' => 'secsyn_node.pages.inc',
      'type' => MENU_LOCAL_TASK,
    )
  );
}

function secsyn_node_preprocess_node(&$vars) {
  if (user_access('syndicate object')) {
    $vars['user_actions']['syndicate'] = array(
      'title' => t('Syndicate'),
      'path' => 'node/' . $vars['node']->nid . '/syndicate',
      'weight' => 50,
    );
  }
}
