<?php

/**
 * Provides a small function that is always available to quickly add an object
 * to the syndication queue.
 *
 * @param string $remote_machine_name The machine name of a remote server OR
 *   the base URL of a server.
 * @param string $profile The name of the profile to queue with
 * @param mixed $object The object to queue for syndication
 * @param boolean $urgent TRUE to use urgent syndication, otherwise FALSE
 * @return boolean TRUE if the object was queued, otherwise FALSE.
 */
function _secsyn_fast_queue($remote_machine_name, $profile, $object, $urgent = FALSE) {
  if ($urgent && (!user_access('urgent syndication'))) {
    $urgent = FALSE;
  }
  $engine = new SecureSyndicationEngine();
  $remote = twoway_server_load($remote_machine_name);
  return $engine->queue($remote['server_connection'], $profile, $object, $urgent);
}

/**
 * Other modules can use this to add the remote server list and common
 * syndication settings to a form.
 *
 * @param array $form FAPI array
 */
function _secsyn_common_fields(&$form) {
  $form['syndication'] = array(
    '#type' => 'fieldset',
    '#collapsible' => TRUE,
    '#title' => t('Syndication Settings'),
  );
  $form['syndication']['remote_server'] = array(
    '#type' => 'select',
    '#options' => twoway_server_list(),
    '#title' => t('Remote Server'),
    '#empty_value' => '',
    '#default_value' => '',
    '#empty_option' => t('Select one...'),
    '#required' => TRUE,
  );
  if (user_access('urgent syndication')) {
    $form['syndication']['urgency'] = array(
      '#type' => 'checkbox',
      '#title' => t('Urgent: Push ASAP'),
    );
  }
  // @todo: hook for other modules to add to this form.
}

/**
 * Implements hook_permission().
 */
function secsyn_permission() {
  return array(
    'syndicate object' => array(
      'title' => t('Queue objects for syndication'),
      'description' => t('Users will be able to queue objects to be syndicated to remove servers'),
    ),
    'bulk syndicate' => array(
      'title' => t('Queue objects in bulk for syndication'),
      'description' => t('Users will be able to queue objects in bulk to be syndicated'),
      'restrict access' => TRUE,
    ),
    'trigger syndication' => array(
      'title' => t('Trigger syndication immediately'),
      'description' => t('Users will be able to trigger the syndication process'),
      'restrict access' => TRUE,
    ),
    'urgent syndication' => array(
      'title' => t('Urgent syndication'),
      'description' => t('Users will be able to trigger urgent syndications'),
      'restrict access' => TRUE,
    ),
    'receive syndication' => array(
      'title' => t('Accept syndication'),
      'description' => t('Users will be able to use the service for syndication'),
      'restrict access' => TRUE,
    )
  );
}

/**
 * Implements hook_menu().
 */
function secsyn_menu() {
  return array(
    // @todo Consider better naming and location for these files
    // (possibly under admin/config?)
    'admin/content/syndication' => array(
      'title' => 'Syndication Command Centre',
      'description' => 'List of all the items on the syndication queue',
      'page callback' => 'secsyn_status_page',
      'access arguments' => array('trigger syndication'),
      'file' => 'secsyn.pages.inc',
      'type' => MENU_NORMAL_ITEM,
    ),
    'admin/content/syndication/report' => array(
      'title' => 'Bridge',
      'description' => 'List of all the items on the syndication queue',
      'page callback' => 'secsyn_status_page',
      'access arguments' => array('trigger syndication'),
      'file' => 'secsyn.pages.inc',
      'type' => MENU_DEFAULT_LOCAL_TASK,
      'weight' => 0,
    ),
    'admin/content/syndication/go' => array(
      'title' => 'Force Syndication',
      'description' => 'Triggers syndication immediately',
      'page callback' => 'secsyn_force_page',
      'access arguments' => array('trigger syndication'),
      'file' => 'secsyn.pages.inc',
      'type' => MENU_LOCAL_ACTION,
      'weight' => 20,
    )
  );
}

/**
 * Implements hook_cron().
 */
function secsyn_cron() {
  // @todo configurable delay setting on how often syndication should run
  // we fire our own pre-cron event in order to let modules act immediately
  // before we syndicate from cron.
  module_invoke_all('secsyn_precron');
  module_load_include('inc', 'secsyn', 'secsyn.functions');
  secsyn_syndicate_all(TRUE);
}

/**
 * Implements hook_twoway_service().
 */
function secsyn_twoway_service() {
  return array(
    'check' => array(
      'callback' => 'secsyn_service_do_check',
      'service_file' => 'services/secsyn.check.inc',
      'description' => 'Verifies which objects need to be synchronized',
    ),
    'sync' => array(
      'callback' => 'secsyn_service_do_sync',
      'service_file' => 'services/secsyn.sync.inc',
      'description' => 'Synchronizes objects with the remote server'
    ),
  );
}