<?php

function secsyn_entity_secsyn_profiles() {
  return array(
    'SecureSyndicationEntityProfile' => t('Entities'),
    'SecureSyndicationVocabularyProfile' => t('Taxonomy Vocabularies'),
    'SecureSyndicationBaseUserProfile' => t('Users (Limited)'),
  );
}

function secsyn_entity_entity_info_alter(&$entity_info) {
  foreach (array_keys($entity_info) as $key) {
    $entity_info[$key]['view modes']['secsyn_preview'] = array(
      'label' => t('Syndication Preview'),
      'custom settings' => TRUE,
    );
  }
}

function secsyn_entity_secsyn_entity_presave(&$object) {
  $info = entity_get_info($object->entity_type);
  if (!empty($info['entity keys']['revision'])) {
    // TODO: Control revisions with a setting (or let others implement the hook?)
    $object->revision = 1;
  }
}

function secsyn_entity_entity_load($entities, $type) {
  foreach ($entities as $entity) {
    $entity->entity_type = $type;
  }
}

module_load_include('inc', 'secsyn_entity', 'secsyn_entity.core');
module_load_include('inc', 'secsyn_entity', 'secsyn_entity.contrib');